import { Job, createJob } from ".";

export const JOB_FACTORIES: Readonly<Record<string, () => Job>> = {
  recruit: () =>
    createJob({
      name: "Recruit",
      stats: {
        maxHealthPoints: 3,
        maxAbilityPoints: 2,
        attack: 4,
        defense: 5,
        arcana: 2,
        spirit: 5,
        speed: 9,
        accuracy: 5,
        evade: 4,
        resist: 5,
        move: 4,
        jump: 2,
      },
      growth: {
        maxHealthPoints: 0.9,
        maxAbilityPoints: 0.55,
        attack: 0.85,
        defense: 0.85,
        arcana: 0.25,
        spirit: 0.25,
        speed: 0.4,
        accuracy: 0.4,
        evade: 0.3,
        resist: 0.25,
      },
    }),
  warrior: () =>
    createJob({
      name: "Warrior",
      stats: {
        maxHealthPoints: 4,
        maxAbilityPoints: 2,
        attack: 6,
        defense: 9,
        arcana: 2,
        spirit: 6,
        speed: 10,
        accuracy: 6,
        evade: 5,
        resist: 5,
        move: 4,
        jump: 1,
      },
      growth: {
        maxHealthPoints: 0.95,
        maxAbilityPoints: 0.6,
        attack: 0.9,
        defense: 0.9,
        arcana: 0.1,
        spirit: 0.3,
        speed: 0.35,
        accuracy: 0.4,
        evade: 0.3,
        resist: 0.2,
      },
    }),
  rogue: () =>
    createJob({
      name: "Rogue",
      stats: {
        maxHealthPoints: 3,
        maxAbilityPoints: 2,
        attack: 5,
        defense: 5,
        arcana: 5,
        spirit: 4,
        speed: 11,
        accuracy: 6,
        evade: 6,
        resist: 5,
        move: 5,
        jump: 3,
      },
      growth: {
        maxHealthPoints: 0.75,
        maxAbilityPoints: 0.75,
        attack: 0.85,
        defense: 0.75,
        arcana: 0.2,
        spirit: 0.2,
        speed: 0.45,
        accuracy: 0.45,
        evade: 0.4,
        resist: 0.2,
      },
    }),
  wizard: () =>
    createJob({
      name: "Wizard",
      stats: {
        maxHealthPoints: 3,
        maxAbilityPoints: 4,
        attack: 2,
        defense: 5,
        arcana: 9,
        spirit: 7,
        speed: 10,
        accuracy: 4,
        evade: 4,
        resist: 7,
        move: 3,
        jump: 2,
      },
      growth: {
        maxHealthPoints: 0.75,
        maxAbilityPoints: 0.9,
        attack: 0.25,
        defense: 0.2,
        arcana: 0.9,
        spirit: 0.7,
        speed: 0.3,
        accuracy: 0.3,
        evade: 0.2,
        resist: 0.5,
      },
    }),
} as const;
